# Generated by Django 5.2.12 on 2026-04-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=10, unique=True)),
                ('text', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('d', 'Daily'), ('w', 'Weekly'), ('m', 'Monthly')], max_length=1)),
                ('priority', models.CharField(choices=[('high', 'High'), ('med', 'Medium'), ('low', 'Low')], default='med', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
