# Generated by Django 5.2.12 on 2026-04-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_taskdefinition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='status',
            field=models.CharField(choices=[('done', 'Completed'), ('wip', 'In Progress'), ('blk', 'Blocked'), ('miss', 'Missed')], max_length=10),
        ),
    ]
