# Generated by Django 5.2.12 on 2026-04-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_tasklog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='duration_mins',
            field=models.IntegerField(default=0, help_text='Time spent in minutes'),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='impact',
            field=models.CharField(choices=[('low', 'Low'), ('med', 'Medium'), ('high', 'High')], default='med', max_length=10),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='outcome',
            field=models.CharField(blank=True, help_text='What was achieved?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='logged_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='task_text',
            field=models.CharField(max_length=500),
        ),
    ]
