# Generated by Django 5.2.12 on 2026-04-22 07:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_tasklog_duration_mins_tasklog_impact_tasklog_outcome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklog',
            name='duration_mins',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='impact',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='outcome',
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='logged_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('wip', 'In Progress'), ('blk', 'Blocked'), ('miss', 'Missed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='task_text',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='GeneralTaskEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('task_id', models.CharField(max_length=10)),
                ('task_text', models.CharField(max_length=500)),
                ('observations', models.TextField(blank=True, help_text='What did you see / check?')),
                ('action_taken', models.TextField(blank=True, help_text='What did you do?')),
                ('outcome', models.TextField(blank=True, help_text='What was the result?')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'General Task Entry',
                'verbose_name_plural': 'General Task Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
