# Generated by Django 5.2.12 on 2026-04-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_tasklog_duration_mins_remove_tasklog_impact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='action_taken',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='observations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='outcome',
            field=models.TextField(blank=True),
        ),
    ]
