# Generated by Django 5.2.12 on 2026-04-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_tasklog_action_taken_tasklog_observations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaltaskentry',
            name='fields_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='generaltaskentry',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('wip', 'In Progress'), ('blk', 'Blocked')], default='done', max_length=10),
        ),
        migrations.AddField(
            model_name='taskdefinition',
            name='fields_schema',
            field=models.JSONField(blank=True, default=list, help_text='List of field names for this task'),
        ),
    ]
