# Generated by Django 5.2.12 on 2026-04-22 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_generaltaskentry_fields_data_generaltaskentry_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('environment', models.CharField(choices=[('prod', 'Production'), ('stag', 'Staging'), ('dev', 'Development')], default='prod', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='action_taken',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='outcome',
        ),
        migrations.AlterField(
            model_name='generaltaskentry',
            name='fields_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='generaltaskentry',
            name='status',
            field=models.CharField(default='done', max_length=20),
        ),
        migrations.AlterField(
            model_name='generaltaskentry',
            name='task_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='generaltaskentry',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_entries', to='tracker.server'),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_logs', to='tracker.server'),
        ),
    ]
