# Generated by Django 5.2.12 on 2026-04-22 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_server_remove_tasklog_action_taken_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('environment', models.CharField(default='Production', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='tasklog',
            name='action_taken',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='observations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='outcome',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='generaltaskentry',
            name='fields_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='generaltaskentry',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('wip', 'In Progress'), ('blk', 'Blocked')], default='done', max_length=10),
        ),
        migrations.AlterField(
            model_name='generaltaskentry',
            name='task_text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='generaltaskentry',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_entries', to='tracker.serverenvironment'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_logs', to='tracker.serverenvironment'),
        ),
        migrations.DeleteModel(
            name='Server',
        ),
    ]
