# Generated by Django 5.2.12 on 2026-04-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_serverenvironment_tasklog_action_taken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaltaskentry',
            name='server',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='server',
        ),
        migrations.AddField(
            model_name='generaltaskentry',
            name='server_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='server_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ServerEnvironment',
        ),
    ]
