# Generated by Django 5.2.12 on 2026-04-22 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_remove_generaltaskentry_server_remove_tasklog_server_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('provider', models.CharField(default='AWS', max_length=100)),
                ('region', models.CharField(default='us-east-1', max_length=50)),
                ('status', models.CharField(choices=[('up', 'Operational'), ('down', 'Down'), ('maint', 'Maintenance')], default='up', max_length=10)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='generaltaskentry',
            name='server_name',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='server_name',
        ),
        migrations.AlterField(
            model_name='alertcheckentry',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertcheckentry',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_entries', to='tracker.server'),
        ),
        migrations.AddField(
            model_name='generaltaskentry',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_entries', to='tracker.server'),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_logs', to='tracker.server'),
        ),
    ]
