# Generated by Django 5.2.12 on 2026-04-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_server_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='server',
            name='region',
        ),
    ]
