# Generated by Django 5.2.12 on 2026-04-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_remove_server_provider_remove_server_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='role',
            field=models.CharField(choices=[('developer', 'DevOps Engineer'), ('team_lead', 'Team Lead'), ('manager', 'Manager')], default='developer', max_length=20),
        ),
    ]
