# Generated by Django 5.2.12 on 2026-04-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_remove_developer_system_role_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='job_title',
            field=models.CharField(blank=True, default='DevOps Engineer', max_length=100),
        ),
        migrations.AlterField(
            model_name='developer',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('tl', 'Team Lead'), ('developer', 'Developer')], default='developer', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
